### ISSUE TITLE
[Bug] Link element selection shows no toolbar

### ISSUE THREAD

**Issue by devgru** [GrapesJS/grapesjs#2196] opened 2019-08-15 13:38 UTC
Steps to reproduce: add Text, select a word, click on Link icon in RTE panel, select a Link.

Expected behaviour: when I select Link I expect it to display toolbar (with 'select parent' button) alongside its badge.

Actual behaviour: If a link was in startup HTML, Link is properly initialised and selecting it results in both badge and toolbar being displayed. Otherwise, if a Link was created via RTE button selecting it results in just badge being displayed.

**Comment by Zachary1748** [comment] 2019-08-15 17:00
May you provide a reproducible demo?

**Comment by devgru** [comment] 2019-08-16 08:57
Problem can be seen on any Grapes page, e.g. https://grapesjs.com/demo.html 
Just create new Link (it will have no toolbar), refresh the page and you can see Link gets its toolbar.
BTW, if you then create new Link within same parent, there will be no toolbar for both of them.

**Comment by devgru** [comment] 2019-08-16 09:02
So, here's default heading:
<img width="782" alt="Screenshot 2019-08-16 11 58 54" src="https://user-images.githubusercontent.com/63065/63156447-5db15c80-c01d-11e9-9e04-12b47ce0d0c3.png">

Creating a Link:
<img width="712" alt="Screenshot 2019-08-16 11 59 04" src="https://user-images.githubusercontent.com/63065/63156484-702b9600-c01d-11e9-8aa7-e39b7826da01.png">

Refreshing the page:
<img width="721" alt="Screenshot 2019-08-16 11 59 12" src="https://user-images.githubusercontent.com/63065/63156512-7d488500-c01d-11e9-87f8-9b9f8023dc45.png">

Adding another Link:
<img width="695" alt="Screenshot 2019-08-16 11 59 22" src="https://user-images.githubusercontent.com/63065/63156537-876a8380-c01d-11e9-94e7-77946f2166b4.png">

First one lost its toolbar:
<img width="675" alt="Screenshot 2019-08-16 11 59 28" src="https://user-images.githubusercontent.com/63065/63156546-905b5500-c01d-11e9-8d15-433b84ac1107.png">

Refreshing the page, links got their toolbars back:
<img width="717" alt="Screenshot 2019-08-16 11 59 39" src="https://user-images.githubusercontent.com/63065/63156576-a6691580-c01d-11e9-800e-237a93ebce4f.png">

**Comment by artf** [comment] 2019-08-24 18:27
Yeah, I'm aware of this, you have to unfocus from the text editor because of the parser triggering on blur. Hope to improve this soon...

**Comment by simplecommerce** [comment] 2019-12-23 13:22
@artf It also applies to any editing that is made within the same text block, for example if you go back and edit a portion of the text and blur, any other content inside will not have the toolbars.

Is there a manual way to fix this for the moment until it is improved?

**Comment by artf** [comment] 2023-07-26 12:45
Closing the issue as it seems to be fixed.

**Closed by artf** 2023-07-26 12:45 UTC
Labels: enhancement, help wanted
