### ISSUE TITLE
BUG: Editor Freeze on loadProjectData 0.21.7

### ISSUE THREAD

**Issue by boardmain** [GrapesJS/grapesjs#5457] opened 2023-10-11 14:26 UTC
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 117.0

### Reproducible demo link

localhost

### Describe the bug

grapesjs": "^0.21.7",

 editor.loadProjectData({
                    "assets": [],
                    "styles": [],
                    "pages": [{ "component": "<div>TEST TEST TEST TEST</div>" }]
                })

editor freeze

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment] 2023-10-12 20:20
Are you able to provide a reproducible demo? Tried your example and I don't see any freeze....

**Comment by artf** [comment] 2023-10-19 18:38
Please @boardmain provide a reproducible demo of your issue. 

Closing this as right now it looks like you're doing something wrong locally as I'm not able to reproduce it.

**Closed by artf** 2023-10-19 18:38 UTC
Labels: more-information-needed

**Comment by antoinematyja** [comment] 2025-01-07 08:30
Hi, I encountered the same issue using Vue 3 and using a vue `ref` to store the editor. Not sure if this is a good idea though.

A code reproduction would be something like:

```
<script setup>
// import vue ref
import { ref } from 'vue'

const editor = ref(null)

editor.value = grapesjs.init({
  container: '#gjs',
  ...
})

// This makes the browser view freeze
editor.loadProjectData({ ... })
</script>

<template>
  <div id="gjs" />
</template>
```

Fix: don't use a `ref` 😅
