### ISSUE TITLE
BUG: cannot "sort" elements of layer panel

### ISSUE THREAD

**Issue by rozek** [GrapesJS/grapesjs#5363] opened 2023-09-05 16:13 UTC
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 1.56.20 Chromium: 115.0.5790.171 (Offizieller Build) (arm64)

### Reproducible demo link

none

### Describe the bug

When I try to reorder the elements on my canvas by sorting them in the layer panel, I repeatedly get the following error message while dragging:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'Canvas')
    at o.selectTargetModel (Sorter.ts:500:27)
    at o.onMove (Sorter.ts:545:10)
    at _e (_executeBound.js:8:65)
    at HTMLDivElement.<anonymous> (bind.js:10:12)
    at HTMLDivElement.<anonymous> (restArguments.js:16:27)
```

Additionally, upon "mouseup", I get the following error message

```
Uncaught TypeError: Cannot read properties of undefined (reading 'method')
    at o.move (Sorter.ts:1253:23)
    at o.endMove (Sorter.ts:1177:25)
    at _e (_executeBound.js:8:65)
    at HTMLDocument.<anonymous> (bind.js:10:12)
    at HTMLDocument.<anonymous> (restArguments.js:16:27)
```

This problem _may_ have been introduced recently as I can remember that sorting worked several days ago...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arbisyarifudin** [comment] 2023-09-06 02:08
Im facing same issue

**Comment by rozek** [comment] 2023-09-06 08:41
`Sorter.ts:500` contains `const cv = this.em!.Canvas`, which is obviously wrong (as `em` _is_ null or undefined)

Unfortunately, I don't currently understand the code with all its abbreviations - but: would a change of line 499 to `if (model?.set && (this.em != null)) {` help here?

**Comment by artf** [comment] 2023-09-09 08:33
Closing as duplicate of https://github.com/GrapesJS/grapesjs/issues/5355

**Closed by artf** 2023-09-09 08:33 UTC
