### ISSUE TITLE
[BUG] Problem with link and CKEditor

### ISSUE THREAD

**Issue by kuhelbeher** [GrapesJS/grapesjs#2828] opened 2020-06-12 14:57 UTC
There is a problem with link and CKEditor. I enabled editable property for <a> tags:
```javascript
CKEDITOR.dtd.$editable.a = 1;
```
And when I doubleclick on the link it is editable, all works as it should. But when I finish editing and trying to edit it again I cannot do it.
![simplescreenrecorder-2020-06-12_17 50 01](https://user-images.githubusercontent.com/37115006/84516172-16940680-acd6-11ea-94cd-b8e37bd1baf1.gif)
Can you help with this?

**Comment by artf** [comment] 2020-06-17 21:50
Please create a reproducible demo

**Comment by kuhelbeher** [comment] 2020-06-24 13:17
@artf Here it is: https://codesandbox.io/s/link-ckeditor-8md7v?file=/src/index.js

**Comment by artf** [comment] 2020-07-05 15:37
I see how the contenteditable remains `false` which is the reason of the bug but I'm not sure what is the cause. It might also be the CKEditor which prevents the propagation for some reason. 
If someone is willing to help I'd really appreciate it.

**Comment by longdoan7421** [comment] 2020-07-15 03:47
The attribute `contenteditable` remains `false`, because CKEditor have already focused into the link when you started edit the second time.
I don't know how to stop that behavior by CKEditor because I don't use CKEditor much. So I did a work around that I modify the `focus` function in `grapesjs-plugin-ckeditor` and move `el.contentEditable = true` to top
```
focus(el, rte) {
      el.contentEditable = true;

      // Do nothing if already focused
      if (rte && rte.focusManager.hasFocus) {
        return;
      }
      // el.contentEditable = true // <-- move this to top
      rte && rte.focus();
}
```
However, this work around has a drawback is that when you started edit the second time, it will show the link editor dialog of CKEditor. But I think that dialog is pretty useless in this case, I decided to disable opening that dialog when double click on link.
```
// Prevent open link editor dialog
rte.on(
    "doubleclick",
    function(evt) {
        const element = evt.data.element;
        if (element.is("a")) {
           evt.stop(); // don't do the other listeners
         }
     },
     null,
     null,
     1
);
```

@kuhelbeher you can see all the changes above in [here](https://codesandbox.io/s/link-ckeditor-wtqn5?file=/src/plugin.js:2483-2782).

**Comment by artf** [comment] 2023-07-26 13:30
Closing this one as it's not related directly to the core

**Closed by artf** 2023-07-26 13:30 UTC
Labels: help wanted
